# Generated by Django 4.1.4 on 2022-12-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.ImageField(default='media/user_images/user.png', null=True, upload_to='user_images'),
        ),
    ]
